version: "3"
services:
    frontend:
        container_name: OfficeQueue-client
        build:
            context: ./client
            dockerfile: Dockerfile
        image: s2team8/office-queue-client
        ports:
            - "3000:3000"
        volumes:
            - ./client:/usr/src/app
    backend:
        container_name: OfficeQueue-server
        build:
            context: ./server
            dockerfile: Dockerfile
        image: s2team8/office-queue-server
        ports:
          - "3001:3001"
        volumes:
            - ./server:/usr/src/app
