version: "3"
services:
    frontend:
        image: se2team8/office-queue:frontend
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./client:/reactapp
             -/reactapp/node_modules
        stdin_open: true
        tty: true
        
    backend:
        image: se2team8/office-queue:backend
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
          - "3001:3001"
        volumes:
            - ./server:/usr/src/app
            - /usr/src/app/node_modules
